// GENERATED by scripts/gen-warmup-fixture.mjs — do not edit by hand; rerun the script.
//
// A recorded TLS 1.3 handshake + one HTTP/1.1 exchange between this package's own client and the
// offline suite's honest test server, over an in-memory pipe. warmup() replays the server's bytes
// through the real parsers, key schedule, AEAD, trust layer and HTTP head parser.
//
// SECURITY NOTE — on the private key below: CLIENT_PRIV_PKCS8 is the fixture client's ephemeral
// X25519 key, and the chain here is synthetic with a reserved-name subject (warmup.invalid,
// RFC 2606). Nothing trusts any of this material: the chain anchors only to its own baked root,
// which is passed explicitly as an anchors-mode trust config inside warmup() and never enters the
// bundled store; the "traffic" it decrypts is this fixture itself. Possession of the key or chain
// grants exactly nothing. It exists so the replay is deterministic without calling
// getRandomValues/generateKey, which the target runtime forbids at module (global) scope.

const B = (s) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));

export const WARMUP_HOSTNAME = "warmup.invalid";
export const WARMUP_NOW = 1893456000000; // fixed epoch ms inside the chain's validity window

const CLIENT_PRIV =
  "MC4CAQAwBQYDK2VuBCIEIKgDjUIyZ1WAQEOJcJ+v5GEtTpdC1Nm9bPqVNp+9eMVP";
const CLIENT_PUB =
  "BsH8Rwt00nHqzF+03rNyNjMunordJ610bPAoD/6k3BY=";
const CLIENT_RANDOM =
  "AwoRGB8mLTQ7QklQV15lbHN6gYiPlp2kq7K5wMfO1dw=";
const SESSION_ID =
  "BRAbJjE8R1JdaHN+iZSfqrXAy9bh7PcCDRgjLjlET1o=";
const CLIENT_HELLO =
  "AQAA6wMDAwoRGB8mLTQ7QklQV15lbHN6gYiPlp2kq7K5wMfO1dwgBRAbJjE8R1JdaHN+iZSfqrXAy9bh7PcCDRgjLjlET1oADBMB" +
  "EwLAK8AvwCzAMAEAAJYAAAATABEAAA53YXJtdXAuaW52YWxpZAAKAAoACAAdABcAGAAZAA0AFgAUBAMFAwYDCAQIBQgGCAcEAQUB" +
  "BgEAEAALAAkIaHR0cC8xLjEAKwAFBAMEAwMAMwAmACQAHQAgBsH8Rwt00nHqzF+03rNyNjMunordJ610bPAoD/6k3BYALQACAQEA" +
  "FwAAAAsAAgEA/wEAAQA=";
const SERVER_BYTES =
  "FgMBAHoCAAB2AwM9CdfJJJXyrkHA20TUyGlMXASSrvNB8Abx0PSwVyq8cCAFEBsmMTxHUl1oc36JlJ+qtcDL1uHs9wINGCMuOURP" +
  "WhMBAAAuACsAAgMEADMAJAAdACCS5ebL5dV3G3hSUdLv6Hm71G6qDPlDa1uuHYNaABWqJxcDAwdYZQdRou7UJWayd8DhsrR7xHoI" +
  "0ZpHl+lkih5uIZz0rTCbJwbzccCjxhl9ukKejYq4QYnz9M41HSIMvcpNwaEt00jEx5H+RLZYtJVBzmVahwrf8ajwRZJe1wiUodYd" +
  "m5vSpchNv+gaz+JhFoDN2fSlWoBepydYnjzJgBxhUAkCRBweMQT/6gLaRfNBw3tPL75tpLUzBJ3oi9hEnaJmbPobYhAXVkRwRWbf" +
  "pQ07izGpFRv7wodZQba8825OCYStsakkSygiGTu/pvqLcsQvFPH/e8HZ3cOoFxZ8gyhPw2MqjoOTSFjq6P2bFiK+ZQiG9tsbxEj1" +
  "ebX8rhmtf/8ESbW0BLaizHtl/SNhF6JYJSyBWizsLW4u6RdxzTw2TO034NKQRZbgoK/z/L8fL5nHSWK8/isusohqwkwmK77xXIPG" +
  "6y5jMYxtEWXBuZxbzzf3MAuuP0HMAo7S6LByMqOxUhUKYMiy0iWkxwex+iur6B1vps2JL+8O1YxTahavJUGzuDMqxFIzXmaMNwZD" +
  "6/h9QwVqz+pUik4LA7DsLyEeEsDKnfzsQh8WqYQbANWDVrUiiZ48mDV8heC0K4g3HAVjdYoJWz1nbob7NW1bmNpY+ISAkaIQfzAt" +
  "VZNwuAV4gRaapGg6NDUCA5hiRjzJVZpAAyL3ypqtt0zSqBTxH/xWqXNSDhM1X54QlFZijPi8IzSGdWKvxMZ1d2KmsXxLXCrBsBzS" +
  "/55GptnFd5Isygjsc0w0PD4FNqUS+eKNoBaeqec0rogXiIhe02HTWCvV0KRP0VxWNMW8XdFzCGG0xNp2QWVfpPE7Lux2kXkWK6sz" +
  "mfZIfrIXCdJvWXUifNWF+jKxUo1UnUqhRYVJCn/XcxpWHALdjVJFFxFLbFblRA7uFdak/q7exlxrUzNStcl+v/f6+vuar/Sh7mPM" +
  "/UVAu2dnxCsfqX+NqSpQo7X2IS2PGA4FZTqWDXgSpkRA5L34PayzqQrMvyR/tErsxfsdHKPFU5FWlGlcNRIt8aP2Ou6a26AanfwA" +
  "Yehc3lI/FLRVk9kaFSZfCcB4z+WMu4JS4uMmAmGm8GWGoNDG/kGFjyWzogUcnEDKFGA8aSB5ZKS7rSgTY4+tHztVWXBM8AMkIogA" +
  "bQ6gifb8sQecHXUovYXHwGjrxBCjTqRhrXqM6KKthcxblPgjvR9p4xW4V5P/atWQIYBCLO6iuEiroz0AyAmqQctGERPHRVKqTfnW" +
  "OIAQ8HlWL1lHXJQG9C/JyTok0JHNQtSw3mo2SUb4S94eoClY9ReXs/64QwVpcxqgPLGQX/ngxAjGvvEjz0gRKjoj3IpVjd7/6R8j" +
  "JHr6yLdOjrxuDaBUO1NaiDXkLzpbEhz3VBsbavPndEHUAYrdgh2nDV/ZaAWO05oLxL5OwzVgoEXz9FJsFg2/PCXHvlI4mH9xiU9b" +
  "/vvTFj/Vey0lEXeMTEIsqjZcBO7sozmtHhjvej/W2qbkiE183OwrDHJOr3dLTzMzqid19sGA6NiLcSST48j/+9wobsbItlSZ3UCS" +
  "4A8g3XVlmYLsWmlkSHzqfR95UTQMdskyHmertwCKiES+f4XxB0d5xjKS2aAWk4XJnvyKXwiECM5zW3DMg3RlEJX5AvUs30KrITyv" +
  "zlJPw0xxBCFdJWLAqWY3V279Ly8o8u5rWcfaXQ0mk6G/XnM5V454sGrCeHhTcDPz0QPekmK51URO+3hYJS5zUuHaf2E1Nq9uKFRD" +
  "9RSnTRvXfzrseKvI7keVuwmJ6QXE6yiOqtyz4QxZnoIWNFX0DFGlov78ZRTCWWGAeEnTTe8j+dkueIOw3A9cjXir7iiuP4SpF43z" +
  "Y9lg1cXE6+8gjwsBR7NgDIO7xQByZmMksxZrXnKErLmp4V/i7i7SBHE2XRoQpxjyzju9ooHZw9Ojxc+rHM1cshkiYLAQwpC2dCRE" +
  "aHBnq2ZEtyXk3fDaJrUYazPXcGhU+6VdTLf2H103fOiWJtrdZfYPYk6QDofkIDvqLEOB0C8ONlV0pwOHjzHEkPCfAQvmkvog0FEg" +
  "h+SUYHS7CO8KFpEtXlVOE494OdgzymSOGOJVQe15srXucdi+ceNGrjSbhVMw7z+bkwYJEz3Ms+UwxiSozsFobczWa9+zdzQrf524" +
  "PNXI6dSWC38H00YpePNhvih7SqKoo78TSWEEieKOZd5QSfSXcQ6Hb/5KRMvvCzcXRbMLJkPtBgNKaWMb4FjNvtqFPCTVWdj1PQRo" +
  "H0tnxKzIggXaqPqXKPiHJqkplj+xUQzk/ty/rptL3iDsmow+niG+h0S62ZXgs3ucuG6wKINczu7vS51T2ds3qQrZTZh5EMIfDSCd" +
  "rsefFwjPASKCc7C4AGrXVvLL6o2K+MZ1UtkFEMToHi++PXLDSSODN1PpYCfHmp+PX1Rs6hK1TzEh/cJdFxm0YO9LJITCStCgMHq/" +
  "od4GGmF29j7vdCY2SKsRhbf3VprEnh/b8e89ttzSZ/j2xZSQ23YVXQBluLYkCOPvhjPq+N0AH+Mjpc3juukXAwMBGX/JuikPTRto" +
  "G6k+VhvA5IABi43hFEZ7lSL38oFHZCCUmpboIWbkz6PNW6Yqp0SBAzd+D1+GD2QFl+ZdAXkUo5p+yTya1IUte+4snmvP5JO9NMZT" +
  "7nV1qsvHpXW2YbLVJuficCuHJkmZbOicQAUe+9Z8wDo41XcwCCpU1AoPxI1uolOcnYA1JQo/MsrQdvNfnIU1TS1IJx2pg5GJffax" +
  "H/nE33cVijW9JHROMolZPrFmYh9jAUEgQdcGQTHtWavcBSy7zMFekpXO4fS3GaBJPHTNwzUkjX+dnlR5C9QVOwEr01BiOoBDicT6" +
  "BjVhg5wRFnnNUeRCybQICyAYpcuKRv8mQyqNWqMfnPAOM6t08tXLfldOyAq9eyeLFwMDABPw6Az9+nivqlKgf1M4sRh9OHlu";
const ROOT_DER =
  "MIIC2jCCAcKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAeMRwwGgYDVQQDDBNXYXJtdXAgRml4dHVyZSBSb290MB4XDTI1MDEwMTAw" +
  "MDAwMFoXDTM1MDEwMTAwMDAwMFowHjEcMBoGA1UEAwwTV2FybXVwIEZpeHR1cmUgUm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEP" +
  "ADCCAQoCggEBALQbVQ1xxCIBOCgWUtgTOvBwwIq3bjj0UMgAqoNeg4FIRbL/57Al9s6E0boVQ7pJZ6p/7XAmZt0GkHgo0C0ghOL9" +
  "Nya/LS2e/uWsHlv/vfTfthiUrgNF2d5QnU3KecuQgFLCaEOZ4KzxipB1VK9V3/qO6B4Bl4S99ie7wLBc1AKThmaC8fhfiOsDzRtW" +
  "iKYCh/rP9HW21kLb5JhSwcN1LjZLPbA2U48yb+6EyL+WIoI5PHUgY8fmHhkcJ+b2JjLrP5gsmE3dmo6IvlOmdPEpIJwPq+zL/u3C" +
  "Efw2xHYDnlJIIqEfWjWNIeJposZAMtaulV/ERIPXY8GHJKLH6KHFBU0CAwEAAaMjMCEwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8B" +
  "Af8EBAMCAgQwDQYJKoZIhvcNAQELBQADggEBAFN90Yri/1pziQhHYEco+oWF7DRzmZwaJT9IrBQxkMa1OzYXTMqcIlwCXg0IpYba" +
  "vZhf1tfAnBqhaFVIVz/IcqaxMTsTzopde9nhaBQHT2ZaTOF56EzfEpKw0wsoXlt8D1GUSzotqodvgkCGMFHEni2ogeUIZAMyLkMX" +
  "URRxMAwd9WNeXnXLw+8ZlthSTxPsIkEjjCkKmRVLdbQe4+MXoMFSPy/qe4KRHh3ImZA13Xa5xHaIjGMGBE8B895hyN5pFeGqjG8u" +
  "j3LCVzeXKAieDuHy7lISp8fL85/IxeG/aPQN3TyeURm03fRHY3+hmY8jShUF/4MZuNerOV5VGSPNUAY=";

export const WARMUP_FIXTURE = {
  clientPrivPkcs8: () => B(CLIENT_PRIV),
  clientPubRaw: () => B(CLIENT_PUB),
  clientRandom: () => B(CLIENT_RANDOM),
  legacySessionId: () => B(SESSION_ID),
  clientHello: () => B(CLIENT_HELLO),
  serverBytes: () => B(SERVER_BYTES),
  rootDer: () => B(ROOT_DER),
};
