// GENERATED by scripts/gen-warmup-fixture.mjs — do not edit by hand; rerun the script.
//
// A recorded TLS 1.3 handshake + one HTTP/1.1 exchange between this package's own client and the
// offline suite's honest test server, over an in-memory pipe. warmup() replays the server's bytes
// through the real parsers, key schedule, AEAD, trust layer and HTTP head parser.
//
// SECURITY NOTE — on the private key below: CLIENT_PRIV_PKCS8 is the fixture client's ephemeral
// X25519 key, and the chain here is synthetic with a reserved-name subject (warmup.invalid,
// RFC 2606). Nothing trusts any of this material: the chain anchors only to its own baked root,
// which is passed explicitly as an anchors-mode trust config inside warmup() and never enters the
// bundled store; the "traffic" it decrypts is this fixture itself. Possession of the key or chain
// grants exactly nothing. It exists so the replay is deterministic without calling
// getRandomValues/generateKey, which the target runtime forbids at module (global) scope.

const B = (s) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));

export const WARMUP_HOSTNAME = "warmup.invalid";
export const WARMUP_NOW = 1893456000000; // fixed epoch ms inside the chain's validity window

const CLIENT_PRIV =
  "MC4CAQAwBQYDK2VuBCIEIGD2kIBgmWlTqN+qzpUvC5PMClhKiudEWslvOrbnG7lq";
const CLIENT_PUB =
  "c4dk24oOgG+LLBpm0e90sFXS+UhcTLZpEIrCDhTPgCo=";
const CLIENT_RANDOM =
  "AwoRGB8mLTQ7QklQV15lbHN6gYiPlp2kq7K5wMfO1dw=";
const SESSION_ID =
  "BRAbJjE8R1JdaHN+iZSfqrXAy9bh7PcCDRgjLjlET1o=";
const CLIENT_HELLO =
  "AQAA9AMDAwoRGB8mLTQ7QklQV15lbHN6gYiPlp2kq7K5wMfO1dwgBRAbJjE8R1JdaHN+iZSfqrXAy9bh7PcCDRgjLjlET1oADBMC" +
  "EwHALMAwwCvALwEAAJ//AQABAAAAABMAEQAADndhcm11cC5pbnZhbGlkAAUABQEAAAAAAAsAAgEAAAoACgAIAB0AFwAYABkAEAAL" +
  "AAkIaHR0cC8xLjEAFwAAAA0AFgAUBAMFAwYDCAQIBQgGCAcEAQUBBgEAKwAFBAMEAwMALQACAQEAMwAmACQAHQAgc4dk24oOgG+L" +
  "LBpm0e90sFXS+UhcTLZpEIrCDhTPgCo=";
const SERVER_BYTES =
  "FgMBAHoCAAB2AwOd1LxJZeGnlrBrfh+XURLQ0+oy/nHBoHi4f2te1UCsgiAFEBsmMTxHUl1oc36JlJ+qtcDL1uHs9wINGCMuOURP" +
  "WhMCAAAuACsAAgMEADMAJAAdACA/u21n72qimI15SHG70pBa5bDie2NJ5jJ3U9mc6quvbhcDAwdo1lcruKbvqnFuYLiYAcl82akL" +
  "xNhbdsBzqLb0/hxNrpwSyceH0iseW8tCkUmLDZSikWT3FIfTy5gxHhzw9jCF20wVsupTSDu1vhVDHVCae5vl4cBbCpAIGP1DfMkG" +
  "fHy2EqaX9Hvhs/f0IxymKE+phAWvFtG8CWhC+jKkOemjTGeYu7Zz92+xZrjqZvItnNzogFojQFYYAiRkNHkWsCvUmwHAMKOIY3H3" +
  "2ov3zLxtAoFB9GwfOOTe4q0h+JBkTzXdc45AcMVZPyjRIGr/2/XDt5F2NZZY53DZAB9Vba8k1IUUo/YgInGXHULRZaootpQzALAP" +
  "2B29d4DezKxA8HaVw3QQsJ8YKGXRoXGsac1/4MwGjj7gUkzwqXHSeNreoBeGkdu6eCLYKqp7ideGeibQ8zIPNjFSUijOnf8kKmsI" +
  "AjkwLoz0W8NFGaw2ZN7vSABDHAqxiP2hVunU5ppnqD9jWtC5ef1rzOw5UYg6YVWZwywR3p04z4F8FZtqNSuYwgnMXN4M54lGPz8Y" +
  "Vw1NE5sCFDKutVJTAnwiae0L8JoFnfVgdV8f4SInPiH3DWLrTmZK2IL0bzUhfB1OGtXdPJ59ZHR8wh3rU1Gcbew3CkzuOa4YX9YC" +
  "kcBhZP2NXGUANcwX1rhVXUCj3jz3z0zn8fIHYqhtFRkAlk0BNr/VPoCnIZZPinARp2CDi9eiUA43zpAXlbwxddmwGTmJSFax2PYs" +
  "OvtpREy/sYGZrO5Yi33NQby+kYkXOxjhnC5KGLKE3O0SA7KbYBzWbWuw15Am0dtizFBam3aZHQzw9IC5MX9p7ENabhSUMjd7QZUV" +
  "fjQRV+ZOndb/vdJG3et7WUa8NzeJ7Gwb+2pzDBj7eu54mtoHmjxu9svI+LEfCc22M7KNydkkNGDlcqJVETx/yS4XZLw2RviZadt3" +
  "mU/9Lzs9Avz+c6+DuMcz0WPqUCuFuD6unOd5c2LikO84RWtfBobEuZwwZhLGM3VwYWdh61wXotjid6aywKl54yM+QvUonvVs9533" +
  "6BG1MRqB7+MuxXBBDOGofZ0ba+3FcF/f9bbbuBBwntU3PlsOzZ5gTeBw/I28MQjOYe4ZfgM3ljTN1BSXokZSC+noYFS73r1cW+oC" +
  "MunCecMP/Vy1AIGWLs87li9FbQBgzF+l1U4bOgE22vCPnC3UC7AH8sGGyPGW5+02ZhPOFOpvh4kp92PbCV5aAF88ZXVEfH5VQmWn" +
  "uR8TLjP6e70NYhnQOWcEQJSCYG85TnsDiRz2/GcQJqDBC/g/Yv7JQhIBicoXhiJyswx9lxrKDsGoxOurY3sJRvgUpvj40EUrTsk8" +
  "6J18td6JJQTnMPiYhSXudXZej0fkcm73DtwX6nEXq05mwwuKiZLSc2fyldVNb7RNyqjnTQLjVCQxtv9Y2Iyl/BSYN4C0dRmAoQur" +
  "mpDtE626fJpP1EBzNmsDlEJoBvPOEVvBEhozdqd8bxkj5p4ePP87nS6diSARiEdmLcSbaOPi6CTckQfnjLfP+Ltws8kC8n2j6lOe" +
  "6MkkRU5vnZzSILVC7pLIDawz4rUfGoVQGU0qWEIFDJ/uHriaq0G7yA3WTUU8Oko8Qxnxc+idtJ/wnTclNH78PkDLPodFb0obT8dh" +
  "m6EkWttPqKty/fMHBUr1afRijHxpO1z6Affz7GMCyJgH8w8lw0R0HDAQTl2+xWXTygGVaKXO4ySqoU2FxANurjp2DpyjUmfDMHOq" +
  "7Ac2rCnSrGbgE7OcPJ00CPqd/6w9EYqt0G3FZaIIIK9n9Tz6WT+8Qh4QtVzyG/6r/WgP6paI4yR9KO1AVr0/UGadjzuk0GXqm2mT" +
  "XiJPpP6YzDkJ1wJCmZ3wHwy2F9SXbv+xLRcYwcTQY+YNxujdiZ+3ZljUULgrIcD3E/RzL9wEYw/fGIYnPqhyJeA3ws73H796u/MX" +
  "D6fwPNL1ImUqJA5dOUMt3RwpdZl8zTmnoDy/T6mpq5agtVAfvJORj7zILPfYohXy2oDTQfuAAqsF0osSm7j4R5LRrzBoFe9FJ6hY" +
  "hiWlYRzObNuDeKX1js6IFzlDBjBaoXJ6S3xO9TED0gfT6aZP109fPSFwYAzitMpSdEKTQlHAavXxppuaztd4Rw+ia6rgEa3dxB3c" +
  "+tZlBeBnmozz2DMenp28CYsPyCfrt9Yv6On8AWbOezmJnpAziJhJrJD3jIKAp02txekEz3eUTNrusCzD+QEBZxZoiq3rr7bY+Wao" +
  "fAbquyVSYB1QurNbLy+LqPFKzZWzrZhcivsRO1ZFjw/wcw/Oeqci570vppJ67QQ1irbEHNb7N8cWIJNAtbYpXRQf5/sp+B1kDdvM" +
  "e1j9sig2JbHPp/7TI7a58ry8Z77+5ivgDSsM3uFmUwbs0/KB9foP2QC4a+pTyN1RXdLnuNkRgWTB6tG05RrCYZfTbTjzfFDWgtzu" +
  "6fJgvActBuvvFjfHx/N3QG2xg5z+txNic7rDJorfBL5d8xK47T+KklNRS6CJws9hBgVjD95kZKU3+o4cNFQE9uZF88yAKSyIk0R2" +
  "bgPUFwMDARkp6obVqB0nPnEgl4GA4oIJuCNzzB7pza1qKxqIqLjVs6ZhzOwPyhyIh1W1nscTrxfpJOOmn9yuOji40yBPz0UGUwqL" +
  "rhWdkK21FpvKx4eoMh/2B1S3XbTA83EIhnQxdwjyutUt+Zf/LCIKC8Q7kCnxqybPek6mxyI9JU6be/I+IV+qsECppD5T73aGmUpa" +
  "5vfNuso40YuTX7a6gUrUPdXluIB4godoeyS9q1AOvgf7hWVIMp/bNl5DOTW/7Lcb/mdlqGMUepXScrEDyTGNyQ/P6R3bOfmpBm5Q" +
  "ONGg9gKm7psWT/U/aK9XQNW+jpqGrBIx9Ws2rbpihOFmzhiPPMhILSLj3rvMyNZoHN8Xv+IhHNqpsCcwSxvg7BcDAwATS/g1rD6Z" +
  "kAgj5tcHEb0GRYv7RQ==";
const ROOT_DER =
  "MIIC2jCCAcKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAeMRwwGgYDVQQDDBNXYXJtdXAgRml4dHVyZSBSb290MB4XDTI1MDEwMTAw" +
  "MDAwMFoXDTM1MDEwMTAwMDAwMFowHjEcMBoGA1UEAwwTV2FybXVwIEZpeHR1cmUgUm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEP" +
  "ADCCAQoCggEBAIRQ0+WIza3mrmr2wDgG0u3kvBYYFp23u+AcofQDWrUKZj/6uOOq2Ur2rZF3cSSkjedqouNvtFfKTA8kUD4IHaM/" +
  "rDjUNBI7ITsyRHieixi39qddXpTgb9+WInm0pyIvAgCLZlyg33AG7y29mEfPTJYAcWaSYRLQwu+/dMAshxC16i3zSU5HleZntE9F" +
  "VJbYR5QGIS6Y5MzU+1hSlXxSbl5boQXTJql1OdWt4t8MU/7voXJhZ6mdGXXiPQXdSrc8txKUJLqd6UgP5AnIhbWhHkfg0MpAXm0Y" +
  "5rrodnclqTNI5ibDDt+ylA9vk5AiCH+mCqPtNd7mERMsP2rpBvRM/EsCAwEAAaMjMCEwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8B" +
  "Af8EBAMCAgQwDQYJKoZIhvcNAQELBQADggEBAHjQ1bWdwKNQpAefj7nyNX7KHdvfNK7TRpAobtunyuEQE6Ia4d1CIOGNHAX87UM2" +
  "4otia7hM4S2oysqvW+HWpMR4cCe2TDofg/nvWo9SOJCsKRcn5caeB3AL0LG7eh97tDoMiytI1xQ2RN/ZajxQ8Fc9WdUjIosiOc5l" +
  "IQFg6pBvzsAhwC2hFuspk31ay/mwE6t5pP+68ZJELqwjBiN6M+vGjIoQ/29tMsgnOaPCXB5vp4gaZpaisu1QiZEG95O7owrJ49+u" +
  "h6JTXWf2j7qxiPqdvqYUGjqZSwKRwZGMYWwIRub/tSdRaRiBpV7QXjarJ8IK9yTAOwe/2fHAX5VbOI0=";

export const WARMUP_FIXTURE = {
  clientPrivPkcs8: () => B(CLIENT_PRIV),
  clientPubRaw: () => B(CLIENT_PUB),
  clientRandom: () => B(CLIENT_RANDOM),
  legacySessionId: () => B(SESSION_ID),
  clientHello: () => B(CLIENT_HELLO),
  serverBytes: () => B(SERVER_BYTES),
  rootDer: () => B(ROOT_DER),
};
